language: java
sudo: false
install: true

addons:
  sonarqube:

script:
  - cd api && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.test.skip=true
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
- oraclejdk8
